import type { Metadata } from "next";
import { Inter, Inter_Tight } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// Inter regular font
const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

// Optional: If you want a monospaced version, Inter_Tight or use something like Roboto Mono
const interTight = Inter_Tight({
  variable: "--font-inter-tight",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${interTight.variable} min-h-screen antialiased`}>
          <Footer/>
        <div className="container">
        <Navbar/>

        {children}
        </div>
      
      </body>
    </html>
  );
}
